### ISSUE TITLE
VisualRust.Build.Rustc.ExecuteInner(), error : The system cannot find the file specified

### ISSUE THREAD

**Issue by melak47** [PistonDevelopers/VisualRust#187] opened 2015-09-28 18:24 UTC
Trying to build any rust project using VS2015 I get the following error:

C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets(53,5): error : The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at VisualRust.Build.Rustc.ExecuteInner()

rustc (1.3), cargo, racer are in my path, I tried both the latest build artifact and the stable version.

**Comment by yacoder** [comment] 2015-09-29 04:02
Looks like a duplicate of #182

**Comment by yacoder** [comment] 2015-09-30 04:08
@melak47, actually the plugin looks for the intalled rust using the registry, not the PATH variable (at least, that is my understanding), e.g. on my machine I have 2 versions of Rust installed (a stable build and a beta), and the plugin actually uses not the one I have in the PATH :-)

Can you check your registry settings to help debug this? Run "regedt32" , then press "Ctrl+F" and search for "Mozilla Foundation", then under that folder find the first value "InstallDir" and see if that path still exists...

Hope this helps.

![rust_registry](https://cloud.githubusercontent.com/assets/5975590/10184189/e921d034-66ed-11e5-9638-1acce548d312.png)

**Comment by retep998** [comment] 2015-09-30 04:27
I'd prefer if VisualRust first checked `PATH` for rustc/cargo, and only use the registry as a fallback.

**Comment by yacoder** [comment] 2015-09-30 04:34
@retep998, I usually don't add them to PATH, when I'm building from the command line I just explicitly call cargo from stable or beta or nightly to know which one I'm building with... maybe it would be better if VisualRust let you select from all the installations it discovers? (eventually) (though I don't know what was the original rationale for not using PATH)

**Comment by melak47** [comment] 2015-09-30 11:43
@yacoder I did indeed have an old 1.3 nightly in the registry which no longer existed on disk, removing it resolves the error!

**Comment by vosen** [comment] 2015-10-18 12:05
I think using registry entries is a less surprising way to discover install paths. If we are getting a support for non-registry install paths it should be part of #172.
Closed by #189.

**Closed by vosen** 2015-10-18 12:05 UTC
