### ISSUE TITLE
Rust installation not found

### ISSUE THREAD

**Issue by martinlierschof** [PistonDevelopers/VisualRust#210] opened 2016-03-06 21:11 UTC
When using visual rust and compiling i always get the error message:
No Rust installation detected. You can download official Rust installer from rust-lang.org/install
I installed a few rust versions inclusive the msvc abi etc.. but the error keeps beeing there. I have the path set to my rust installation and the rust src env path.
I use visual studio 2015. I tried with latest build of visual rust and latest stable.
Can you help me with that?

**Comment by tommiv** [comment] 2016-03-07 00:09
Same here. Rust compiler (MSVC ABI, x64) installed and bin directory have added to env.path. 

```
> rustc --version
rustc 1.7.0 (a5d1e7a59 2016-02-29)
```

**Comment by Shadowraix** [comment] 2016-03-07 16:50
Same here. Tried all versions with Rust 1.7.0 and Visual Rust 0.1.1 still no installation found.

**Comment by mogu84** [comment] 2016-03-09 09:33
This seems to be a problem with the new version (1.7.0) of Rust.

A temporary workaround can be achieved by setting a windows registery key with regedit into:
  Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla Foundation\Rust stable (64-bit)\1.7\

And there you need to add a new string value with data of your rust install directory.
   - For example: C:\Program Files\Rust stable MSVC 1.7

After this Visual Studio should compile normally.
This same workaround was discussed in #209 and #187

**Comment by tommiv** [comment] 2016-03-09 09:35
Should we report to the Rust installer maintainers then? Is this a bug or just a breaking change?

**Comment by dimitri-xyz** [comment] 2016-03-09 23:12
I have the same problem with the same versions cited by @tommiv

**Comment by vosen** [comment] 2016-03-09 23:35
@tommiv Sure, it's a change on the Rust installer maintainers side, but they never commited to keeping the paths stable between release and it's on me to keep up with the changes to the installer, so no reason for reporting it to them.
I've pushed out here and on VS Gallery a new version 0.1.2 that should fix this problem.

**Comment by waynenilsen** [comment] 2016-06-03 17:55
I am also getting this message using rustup-rs on windows 7 using 0.1.2

**Comment by mjfmechanic** [comment] 2016-07-01 20:48
I know this may be basic, but I haven't heard anyone mention this; did you put the installation in your OS environment variables path? Depending if you are using windows/mac, the variable path should already be there and look something like this under system variables ex: variable will be path and value will be C:\Program Files\Rust stable MSVC 1.9\bin; (There's a long list of programs there so copy and past into a text file or something to see all the paths).

Again sorry for the basics and I know everyone is sharp but covering all bases:
right click on "my computer" or "This PC" in your explorer nav window, properties, advanced system settings, Advanced, environment variables, and edit variable named path to show where the location of your Rust version is. Remember to put semi-colons on both sides of your entry. If it's already there, I also added it to my user variable path by creating a RUST_SRC_PATH variable and then also adding the location under values all the way up to the bin file. ex. C:\Program Files\Rust stable MSVC 1.9\bin;

Hope this helps or if not, at least the bases were covered.

-Mike

**Comment by Thomas-Fleming** [comment] 2016-08-04 22:34
Seems to now be resolved for me. First I installed Visual Rust then attempted to compile a basic hello_world.rs app. Got the rust installation not found error. Downloaded the official rust installer and installed. Hit rebuild and everything built fine.

>rustc --version
rustc 1.10.0 (cfcb716cf 2016-07-03)

**Comment by Boddlnagg** [comment] 2016-08-30 11:34
I think this was a duplicate of #207, which has been fixed.

**Closed by Boddlnagg** 2016-08-30 11:34 UTC

**Comment by Pzixel** [comment] 2017-02-22 23:29
Same here. Have `C:\Users\Alex\.cargo\bin` in PATH with `rustc` inside (installed 1.17.1 from official site with all defaults).

**Comment by bbi-ashmatheson** [comment] 2017-05-18 23:42
Just installed Visual Rust on VS 2015 and getting this as well.
```
C:\Users\xxNNxx>rustc --version
rustc 1.17.0 (56124baa9 2017-04-24)
```
