### ISSUE TITLE
Cannot find file

### ISSUE THREAD

**Issue by martindevans** [PistonDevelopers/VisualRust#182] opened 2015-09-06 21:17 UTC
I just installed VisualRust into vs2013 (Windows 10) and created a test executable project. The code of main.rs is unchanged from the initial "hello, world" printing. When I click run I get the following error:

```
Error	1	The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at VisualRust.Build.Rustc.ExecuteInner()	C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets	53	5	Test
```

I have rustc installed and in my path. Running rustc -V gets me this:

 > PS C:\Users\Martin> rustc -V
 > rustc 1.3.0-beta.1 (dc12f5ee1 2015-08-06)

I'm not certain if it is relevant, but running cargo -V gets me:

 > PS C:\Users\Martin> cargo -V
 > cargo 0.4.0-nightly (553b363 2015-08-03) (built 2015-08-03)

**Comment by yacoder** [comment] 2015-09-30 04:35
@martindevans, can you check your registry settings, as described in #187? Just want to confirm it is the root cause, so that we can fix properly.

**Comment by martindevans** [comment] 2015-09-30 15:17
Yep, this is a duplicate of that other issue. I had an old rust in the registry, deleting that fixed the issue.

**Comment by Boddlnagg** [comment] 2015-09-30 20:38
Closing as duplicate of #187

**Closed by Boddlnagg** 2015-09-30 20:38 UTC
